# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=b'title', verbose_name='slug')),
                ('title', models.CharField(max_length=125)),
                ('starts_on', models.DateTimeField()),
                ('ends_on', models.DateTimeField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-starts_on'],
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=b'title', verbose_name='slug')),
                ('title', models.CharField(max_length=75, unique=True)),
                ('sale_starts_on', models.DateTimeField()),
                ('sale_ends_on', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_assigned', models.IntegerField()),
            ],
            options={
                'ordering': ['-sale_starts_on'],
                'verbose_name_plural': 'Tickets',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='tickets',
            field=models.ManyToManyField(to='events.Ticket'),
        ),
    ]
